export enum AppRoutes {
  MAIN = 'main',
  PLACE_DETAILS = 'details',
  JOURNAL = 'journal',
  JOURNAL_ARTICLE = 'journalArticle',
  ABOUT = 'about',
  CONTACTS = 'contacts',
  PROFILE = 'profile',
  MY_REVIEWS = 'myReviews',
  LOGIN = 'login',
  RESET_PASSWORD = 'resetPassword',
  CONFIRM_EMAIL = 'confirmEmail',
  NOT_FOUND = 'not_found',
  PRIVACY = 'privacy',
  DISCLAIMER = 'disclaimer',
  PLACE_PAGE = 'placePage',
  NEIGHBORHOOD = 'neighborhood',
}

export const RoutePaths: Record<AppRoutes, string> = {
  [AppRoutes.MAIN]: '/',
  [AppRoutes.PLACE_DETAILS]: '/details',
  [AppRoutes.PLACE_PAGE]: 'place/:id',
  [AppRoutes.JOURNAL]: 'journal',
  [AppRoutes.JOURNAL_ARTICLE]: 'journal/:slug',
  [AppRoutes.ABOUT]: 'about',
  [AppRoutes.CONTACTS]: 'contacts',
  [AppRoutes.MY_REVIEWS]: 'my-reviews',
  [AppRoutes.PROFILE]: 'profile',
  [AppRoutes.LOGIN]: 'login',
  [AppRoutes.RESET_PASSWORD]: 'reset-password',
  [AppRoutes.CONFIRM_EMAIL]: 'confirm-email',
  [AppRoutes.NOT_FOUND]: '*',
  [AppRoutes.PRIVACY]: 'privacy-policy',
  [AppRoutes.DISCLAIMER]: 'disclaimer',
  [AppRoutes.NEIGHBORHOOD]: 'neighborhood/:neighborhood',
};
