export enum AppRoutes {
  MAIN = 'main',
  PLACE_DETAILS = 'details',
  BLOG = 'blog',
  ABOUT = 'about',
  CONTACTS = 'contacts',
  PROFILE = 'profile',
  MY_REVIEWS = 'myReviews',
  LOGIN = 'login',
  CONFIRM_EMAIL = 'confirmEmail',
  NOT_FOUND = 'not_found',
  PRIVACY = 'privacy',
  DISCLAIMER = 'disclaimer',
  PLACE_PAGE = 'placePage',
}

export const RoutePaths: Record<AppRoutes, string> = {
  [AppRoutes.MAIN]: '/',
  [AppRoutes.PLACE_DETAILS]: '/details',
  [AppRoutes.PLACE_PAGE]: ':id',
  [AppRoutes.BLOG]: 'blog',
  [AppRoutes.ABOUT]: 'about',
  [AppRoutes.CONTACTS]: 'contacts',
  [AppRoutes.MY_REVIEWS]: 'my-reviews',
  [AppRoutes.PROFILE]: 'profile',
  [AppRoutes.LOGIN]: 'login',
  [AppRoutes.CONFIRM_EMAIL]: 'confirm-email',
  [AppRoutes.NOT_FOUND]: '*',
  [AppRoutes.PRIVACY]: 'privacy-policy',
  [AppRoutes.DISCLAIMER]: 'disclaimer',
};
